name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout the actions
      uses: actions/checkout@v3
    -
      name: Build docker img
      run: docker build . --file Dockerfile --tag alintoma/php:$(date +%s)
